// <auto-generated />
using System;
using FantasyGame.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FantasyGame.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230331134939_Partida seed")]
    partial class Partidaseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FantasyGame.Models.Data.Entities.Campeonato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRealizacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("campeonatos");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            DataRealizacao = new DateTime(2023, 1, 1, 19, 34, 13, 856, DateTimeKind.Unspecified).AddTicks(690),
                            Nome = "Brasileirão"
                        });
                });

            modelBuilder.Entity("FantasyGame.Models.Data.Entities.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampeonatoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("Time1Gols")
                        .HasColumnType("int");

                    b.Property<int>("Time1Id")
                        .HasColumnType("int");

                    b.Property<int>("Time2Gols")
                        .HasColumnType("int");

                    b.Property<int>("Time2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.HasIndex("Time1Id");

                    b.HasIndex("Time2Id");

                    b.ToTable("Partidas");

                    b.HasData(
                        new
                        {
                            Id = 500,
                            CampeonatoId = 1000,
                            Data = new DateTime(2023, 1, 1, 19, 34, 13, 856, DateTimeKind.Unspecified).AddTicks(690),
                            Time1Gols = 3,
                            Time1Id = 500,
                            Time2Gols = 2,
                            Time2Id = 501
                        },
                        new
                        {
                            Id = 501,
                            CampeonatoId = 1000,
                            Data = new DateTime(2023, 1, 1, 19, 34, 13, 856, DateTimeKind.Unspecified).AddTicks(690),
                            Time1Gols = 2,
                            Time1Id = 500,
                            Time2Gols = 3,
                            Time2Id = 502
                        },
                        new
                        {
                            Id = 502,
                            CampeonatoId = 1000,
                            Data = new DateTime(2023, 1, 1, 19, 34, 13, 856, DateTimeKind.Unspecified).AddTicks(690),
                            Time1Gols = 1,
                            Time1Id = 500,
                            Time2Gols = 1,
                            Time2Id = 503
                        },
                        new
                        {
                            Id = 503,
                            CampeonatoId = 1000,
                            Data = new DateTime(2023, 1, 1, 19, 34, 13, 856, DateTimeKind.Unspecified).AddTicks(690),
                            Time1Gols = 5,
                            Time1Id = 501,
                            Time2Gols = 4,
                            Time2Id = 502
                        },
                        new
                        {
                            Id = 504,
                            CampeonatoId = 1000,
                            Data = new DateTime(2023, 1, 1, 19, 34, 13, 856, DateTimeKind.Unspecified).AddTicks(690),
                            Time1Gols = 4,
                            Time1Id = 501,
                            Time2Gols = 2,
                            Time2Id = 503
                        },
                        new
                        {
                            Id = 505,
                            CampeonatoId = 1000,
                            Data = new DateTime(2023, 1, 1, 19, 34, 13, 856, DateTimeKind.Unspecified).AddTicks(690),
                            Time1Gols = 3,
                            Time1Id = 502,
                            Time2Gols = 1,
                            Time2Id = 503
                        });
                });

            modelBuilder.Entity("FantasyGame.Models.Data.Entities.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Times");

                    b.HasData(
                        new
                        {
                            Id = 500,
                            Nome = "Internacional"
                        },
                        new
                        {
                            Id = 501,
                            Nome = "São paulo"
                        },
                        new
                        {
                            Id = 502,
                            Nome = "Flamengo"
                        },
                        new
                        {
                            Id = 503,
                            Nome = "Santos"
                        });
                });

            modelBuilder.Entity("FantasyGame.Models.Data.Entities.Partida", b =>
                {
                    b.HasOne("FantasyGame.Models.Data.Entities.Campeonato", "Campeonato")
                        .WithMany("Partidas")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyGame.Models.Data.Entities.Time", "Time1")
                        .WithMany()
                        .HasForeignKey("Time1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FantasyGame.Models.Data.Entities.Time", "Time2")
                        .WithMany()
                        .HasForeignKey("Time2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campeonato");

                    b.Navigation("Time1");

                    b.Navigation("Time2");
                });

            modelBuilder.Entity("FantasyGame.Models.Data.Entities.Campeonato", b =>
                {
                    b.Navigation("Partidas");
                });
#pragma warning restore 612, 618
        }
    }
}
